-- Create account table
CREATE TABLE ACCOUNT (
    USERNAME VARCHAR(30) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(30),
	FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    FULL_NAME VARCHAR(50), 
    ROLE INT
);

-- Create shop table
CREATE TABLE SHOP (
	SHOP_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	SHOP_NAME NVARCHAR(50),
	MAP NVARCHAR(100),
	DATE_CREATED DATETIME,
	PHONE NVARCHAR(11),
	IMAGE NVARCHAR(30),
	TIME_OPEN DATETIME,
	TIME_CLOSE DATETIME,
	STATUS TEXT,
	DISCOUNT DOUBLE,
	VIEW NVARCHAR(30)
);

-- Create save table
CREATE TABLE SAVE (
	SAVE_ID INT,
	USERNAME VARCHAR(30),
	SHOP_ID INT
);

-- Create comment table
CREATE TABLE COMMENT (
	COMMENT_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	USERNAME VARCHAR(30),
	SHOP_ID INT,
	CONTENT_COMMENT TEXT,
	DATE_CREATED DATETIME
);

-- Create rate table
CREATE TABLE RATE (
	RATE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	SHOP_ID INT,
	USERNAME VARCHAR(30),
	SCORE INT
);

-- Create type table
CREATE TABLE TYPE (
	TYPE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TYPE_NAME NVARCHAR(50)
);

-- Create foods table
CREATE TABLE FOODS (
	FOOD_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	SHOP_ID INT,
	FOOD_NAME NVARCHAR(50)
);

-- Create type_shop table
CREATE TABLE TYPE_SHOP (
	TYPE_ID INT,
	SHOP_ID INT
);
