-- Create account table
CREATE TABLE ACCOUNT (
    USERNAME VARCHAR(30) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(30),
	FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    FULL_NAME VARCHAR(50), 
    ROLE INT
);

-- Create save table
CREATE TABLE SAVE (
	SAVE_ID INT NOT NULL,
	USERNAME VARCHAR(30),
	SHOP_ID INT NOT NULL
);